djangoProject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from forum import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# configure the static and media directory


forum/urls.py
from django.urls import path

from forum import views

app_name = 'forum'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('publish/', views.publish, name='publish'),
    path('register/', views.register, name='register'),
    path('admin/', views.admin, name='admin'),
    path('admin_page/', views.admin_page, name='admin_page'),
    path('delete_post/<id>', views.delete_post, name='delete_post'),
    path('topic/<slug:topic_name_slug>/', views.topic, name='topic'),
    path('post/<id>/', views.post, name='post'),
    path('comment/<id>/', views.comment, name='comment'),
    path('published/', views.published, name='published'),
    path('likes/<id>/',views.IncreaseLikesView.as_view(), name='increase_likes'),
]

forum/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify


# Create your models here.

class UserProfile(models.Model):
    NAME_MAX_LENGTH = 30
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    sex = models.CharField(max_length=10, blank=True, null=True)
    post_number = models.IntegerField(default=0)
    like_number = models.IntegerField(default=0)
    follow_number = models.IntegerField(default=0)
    follower_number = models.IntegerField(default=0)
    follow_to = models.TextField(null=False, default="")
    follow_by = models.TextField(null=False, default="")
    picture = models.ImageField(upload_to='profile_images', blank=True)
    is_muted = models.BooleanField(default=False)

    # customise get set method for two list
    def set_follow_to_list(self, element):
        if self.follow_to:
            self.follow_to = self.follow_to + "," + element
        else:
            self.follow_to = element

    def get_follow_to_list(self):
        if self.follow_to:
            return self.follow_to.split(",")

    def set_follow_by_list(self, element):
        if self.follow_by:
            self.follow_by = self.follow_by + "," + element
        else:
            self.follow_by = element

    def get_follow_by_list(self):
        if self.follow_by:
            return self.follow_by.split(",")

    # toString
    def __str__(self):
        return self.user.username


# Also can be called Category or topic
class Module(models.Model):
    NAME_MAX_LENGTH = 50
    DES_MAX_LENGTH = 50
    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    description = models.CharField(max_length=DES_MAX_LENGTH)
    create_time = models.DateTimeField(auto_created=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Module, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


# Manager class, not real model
class PostManage(models.Manager):
    def create_post(self, title, content):
        post = self.create(title=title, content=content)
        return post

    def get_query(self):
        return super(PostManage, self).get_queryset().filter(is_deleted=False)


class Post(models.Model):
    TITLE_MAX_LENGTH = 30
    title = models.CharField(max_length=TITLE_MAX_LENGTH, null=False)
    content = models.TextField('content', blank=True, null=True)
    picture = models.ImageField(upload_to='post_images', blank=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    comment_number = models.IntegerField(default=0)
    top = models.BooleanField(default=False)
    create_time = models.DateTimeField(auto_created=True,auto_now=True, null=False)
    update_time = models.DateTimeField(auto_now=True)
    # not truly delete in database, but marked as deleted, so it would not be queried out
    is_deleted = models.BooleanField('isDelete', default=False)
    delete_time = models.DateTimeField('deleteTime', blank=True, null=True)
    objects = models.Manager()
    posts = PostManage()
    parent_module = models.ForeignKey(Module, on_delete=models.CASCADE)
    poster = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


# It can also write in UserProfile, but separates in order to share the load of UserProfile table
class StarContent(models.Model):
    username = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    stared_post = models.TextField(null=True, blank=False)

    def __str__(self):
        return self.username


class Comment(models.Model):
    # one user only make a Comment to another user in a post
    comment_by = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='commenter')
    comment_to = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='receiver')
    comment_in = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField(null=False, blank=False)
    # picture??? picture = models.ImageFiled()
    create_time = models.DateTimeField(auto_now_add=True)

    # there is no is_deleted filed in this class, so the comment can be truly be deleted

    def __str__(self):
        return self.content

forum/forms.py
from django import forms
from django.contrib.auth.models import User
from forum.models import *

# record user's account and password
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

# record user's profile, but not in use for now
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)

# post form is used to record posts
class PostForm(forms.ModelForm):
    title = forms.CharField(max_length=50)
    content = forms.CharField(max_length=1000)
    parent_module = forms.ChoiceField(initial=1, choices=(
        ('hot posts', 'hot posts'), ('sale of used item', 'sale of used item'), ('flats to rent', 'flats to rent'), ('activity', 'activity'), ('university', 'university'),
        ('coffee break', 'coffee break')))


    class Meta:
        model = Post
        fields = ('title', 'content', 'picture')

forum/views.py
from base64 import standard_b64decode

from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from forum import models
# from numpy import true_divide
from forum.forms import PostForm, UserForm, UserProfileForm
from forum.models import Module, Post, UserProfile, Comment
from django import forms
from django.views import View


# Create your views here.

# this is the home page, show topics
def index(request):
    topic_list = Module.objects.order_by('create_time')[:6]
    standard_list = Module.objects.order_by('create_time')[:6]
    for topic in standard_list:
        topic.name = str.lower(topic.name)
        topic.name = topic.name.replace(" ", "-")

    context_dict = {}
    context_dict['topics'] = topic_list
    context_dict['standards'] = standard_list

    return render(request, 'forum/index.html', context=context_dict)


def about(request):
    context_dict = {}

    return render(request, 'forum/about.html', context_dict)


@login_required
def published(request):
    context_dict = {}

    return render(request, 'forum/published.html', context_dict)

# for user to login
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                next = request.POST.get('next')
                if next:
                    redirect(next)
                return JsonResponse(data={
                    'code': 0,
                    'msg': 'login success',
                    'data': {
                        'url': reverse('forum:index'),
                        'next': next
                    }
                })
            else:
                return JsonResponse(data={
                    'code': -1,
                    'msg': 'user is inactive',
                    'data': {}
                })
        else:
            return JsonResponse(data={
                'code': -1,
                'msg': 'Invalid login details supplied.',
                'data': {}
            })
    else:
        return render(request, 'forum/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('forum:index'))

# for user to regist
def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            return JsonResponse(data={
                'code': 0,
                'msg': 'ok',
                'data': {'url': reverse('forum:login')}
            })

        else:
            return JsonResponse(data={
                'code': -1,
                'msg': str(user_form.errors)
            })
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request, 'forum/register.html',
                  context={'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

# for admin to login
def admin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username == 'admin' and password == '123456':
            # admin login successful
            return redirect(reverse('forum:admin_page'))
        else:
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'forum/admin.html')


def admin_page(request):
    return render(request, 'forum/admin_page.html', {"post_form": Post.objects.all()})


@login_required
def delete_post(request, id):
    p = Post.objects.get(id=id)
    p.is_deleted = True
    p.delete_time = timezone.now()
    p.save()
    return HttpResponseRedirect(reverse('forum:admin_page'))

# used in topic page to see the list of posts in the topic
@login_required
def topic(request, topic_name_slug):
    context_dict = {}
    try:
        topic_list = Module.objects.order_by('create_time')[:6]
        topic = Module.objects.get(slug=topic_name_slug)
        post_list_before = Post.posts.filter(parent_module=topic)
        post_list = post_list_before.order_by('-create_time')[:20]
        standard_list = Module.objects.order_by('create_time')[:6]
        for standard in standard_list:
            standard.name = str.lower(standard.name)
            standard.name = standard.name.replace(" ", "-")
        context_dict['posts'] = post_list
        context_dict['topic'] = topic
        context_dict['topiclist'] = topic_list
        context_dict['standards'] = standard_list
    except Module.DoesNotExist:
        context_dict['posts'] = None
        context_dict['topic'] = None
        context_dict['topiclist'] = None
        context_dict['standards'] = None
    return render(request, 'forum/topic.html', context=context_dict)

# used to read the post
@login_required
def post(request, id):
    context_dict = {}
    try:

        post = Post.posts.get(id=id)
        topic = post.parent_module.name
        topic = str.lower(topic)
        topic = topic.replace(" ", "-")

        comments = Comment.objects.filter(comment_in=post).all()
        for comment in comments:
            # print("#########")
            print(comment)
        context_dict['post'] = post
        context_dict['topic'] = topic
        context_dict['comments'] = comments
    except Post.DoesNotExist:
        context_dict['post'] = None
        context_dict['topic'] = None
    return render(request, 'forum/post.html', context_dict)

# used to publish a post
@login_required
def publish(request):
    standard_list = Module.objects.order_by('create_time')[:1]
    for topic in standard_list:
        topic.name = str.lower(topic.name)
        topic.name = topic.name.replace(" ", "-")

    context_dict = {}
    context_dict['standards'] = standard_list

    if request.method == "POST":
        post_form = PostForm(request.POST)
        title = post_form.data.get("title")
        content = post_form.data.get("content")
        parent_module_name = post_form.data.get("parent_module")
        print(parent_module_name)
        parent_module = Module.objects.get(name=parent_module_name)
        user = User.objects.get(username=request.user.username)
        userprofile = UserProfile.objects.get(user=user)
        if post_form.is_valid():
            post = Post.posts.create(title=title, content=content, parent_module=parent_module, poster=userprofile)
            if 'picture' in request.FILES:
                post.picture = request.FILES['picture']
            post.save()
            return redirect('forum:index')
        else:
            print(post_form.errors)

    else:
        post_form = PostForm()

    return render(request, 'forum/publish.html', context_dict)

@login_required
def comment(request,id):

    if request.method == "POST":
        try:
            content = request.POST.get('content')
            user = User.objects.get(username=request.user.username)
            userprofile = UserProfile.objects.get(user=user)
            post = Post.objects.get(id=id)

            comment = Comment(
                comment_by = userprofile,
                comment_to = userprofile,
                comment_in = post,
                content = content
            )
            comment.save()
        except Exception as e:
            print(e)
            return redirect('forum:index')

        return redirect(reverse('forum:post',kwargs={'id':id}))


# not in use for now
class IncreaseLikesView(View):
    def post(self, request, *args, **kwargs):
        post = Post.posts.get(id=kwargs.get('id'))
        post.likes += 1
        post.save()
        return HttpResponse('success')

templates/forum/about.html
{% extends 'forum/base.html' %}
{% load staticfiles %}


{% block title_block %}
    About 
{% endblock %}

<!-- nothing important here -->
{% block body_block %}
    <link rel="stylesheet" href="/static/css/about.css">
    <div>
        <p class="about">
            This webiste is built by five students from University of Glasgow.
        </p>
    </div>
    
{% endblock %}

templates/forum/admin.html
{% extends 'forum/base.html' %}

{% block title_block %}
Admin login
{% endblock %}

<!-- Admin login  -->
{% block body_block %}
<link rel="stylesheet" href="/static/css/admin.css">

<div class="container login_out">
    <a href="{% url 'forum:login' %}" class="text-decoration-none">User login</a>
    <h1>Admin login</h1>
    <form id="login_form" method="post" action="{% url 'forum:admin' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputEmail1">Username</label>
            <input type="text" name="username" class="form-control" id="exampleInputEmail1"
                aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" name="password" class="form-control" id="exampleInputPassword1">
        </div>

        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-dark" style="margin-top: 20px">Login</button>
        </div>
    </form>
</div>
{% endblock %}

templates/forum/admin_page.html
{% extends 'forum/base.html' %}

{% block title_block %}
Admin Page
{% endblock %}

<!-- Admin login  -->
{% block body_block %}
<link rel="stylesheet" href="/static/css/admin.css">
<div style="width: 100%;height: 60%;">
    <div class="main_out">
        <div class="span4">
            <div class="list_out">
                <span class="post_id bold">id</span>
                <span class="post_title bold">title</span>
                <span class="post_poster bold">poster</span>
                <span class="post_create_time bold">create time</span>
                <span class="post_likes bold">likes</span>
                <span class="post_views bold">views</span>
                <span class="post_delete bold">action</span>
            </div>
            {% for post in post_form %}
            {% if post.is_deleted == False %}
            <div class="list_out">
                <span class="post_id">{{post.id}}</span>
                <span class="post_title">{{post.title}}</span>
                <span class="post_poster">{{post.poster.name}}</span>
                <span class="post_create_time">{{post.create_time}}</span>
                <span class="post_likes">{{post.likes}}</span>
                <span class="post_views">{{post.views}}</span>
                <span class="post_delete">
                    <a href="{% url 'forum:delete_post' post.id %}">delete</a>
                </span>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <a class="btn btn-dark" style="margin-top: 20px" href="{% url 'forum:admin' %}">Log out</a>
    </div>
</div>
{% endblock %}

templates/forum/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- stylesheet -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    

    <title>
        Glasgow Online Forum -
        {% block title_block %}
        {%  endblock %}
    </title>
</head>
<body>
    <h1>
        {% block header_block %}
            
        {% endblock %}
       <!-- create header using bootstrap -->
        <header class="py-3 mb-4 border-bottom">
            <div class="container d-flex flex-wrap justify-content-around">
                <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-clouds-fill" viewBox="0 0 16 16">
                        <path d="M11.473 9a4.5 4.5 0 0 0-8.72-.99A3 3 0 0 0 3 14h8.5a2.5 2.5 0 1 0-.027-5z"/>
                        <path d="M14.544 9.772a3.506 3.506 0 0 0-2.225-1.676 5.502 5.502 0 0 0-6.337-4.002 4.002 4.002 0 0 1 7.392.91 2.5 2.5 0 0 1 1.17 4.769z"/>
                    </svg>
                    <span class="fs-3">Welcome to Glasgow Online Forum</span>
                </a>

                <div class="text-end ">
                    {% if not request.user.is_authenticated %}
                        <a class="btn btn-dark" href="{% url 'forum:login' %} " role="button">Login</a>
                        <a class="btn btn-dark" href="{% url 'forum:register' %} " role="button">Sign up</a>
                    {% else %}
                        <span style="font-size: 16px">{{ request.user.username }}</span> <a class="btn btn-dark" href="{% url 'forum:logout' %} " role="button">Logout</a>
                    {% endif %}

                </div>
            </div>
          </header>  
          
    </h1>
    <div>
        {% block body_block %}
        {% endblock %}
    </div>
    <!-- create footer using bootstrap -->
    <div class="footer-container">
        <div class="container">
            <footer class="footer">
                <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                    <li>
                        <a href="{% url 'forum:index' %}" class="nav-link px-2 text-muted">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'forum:about' %}" class="nav-link px-2 text-muted">About</a>
                    </li>
                </ul>
                <p class="text-center text-muted">© 2022 Glasgow Online Forum</p>
            </footer>
        </div>
        

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
    {% block js %}
    {% endblock %}
</body>
</html>

templates/forum/publish.html
{% extends 'forum/base.html' %}

{% block title_block %}
    Publish a post
{%  endblock %}



{% block body_block %}
<!-- Return to the topic page -->
<div style="position:relative;left:120px;">
<a href="{% url 'forum:topic' standards.0.name %}"> <button type="button">Return</button></a> <br />
<body class="home" style="font-size: 18px">
    
    
    <h3>Publish a post</h3>
    <!-- get the information input from the users -->
    <form accept-charset="UTF-8" action="{% url 'forum:publish' %}" class="publish" id="new_topic" method="post"  enctype="multipart/form-data">
        {% csrf_token %}
        <table width="100%" border="0" cellspacing="0" cellpadding="6">
            <colgroup>
                <col width="140">
                <col>
            </colgroup>
            <tbody>
    
            <tr>
                <th>Title</th>
                <td>
                    <label>
                        <input required id="topic_title" maxlength="80" name="title" size="60" type="text">
                    </label>
                </td>
            </tr>

            <tr>
                <th valign="top">Content</th>
                <td>
                    <div class="body_count">
                        <textarea style="width: 700px;" cols="62" rows="20" name="content"></textarea>
                    </div>
                </td>
            </tr>
    
            <tr>
                <th>Cover image</th>
                <td>
    
                    <div>
                        <input type="file" name="picture" accept="image/*">
                    </div>
                </td>
            </tr>
    
            <tr>
                <th>Topic</th>
                <td>
                    <div>
                        <select name="parent_module">
                            <option value ="hot posts">Hot Posts</option>
                            <option value ="sale of used item">Sale of Used Items</option>
                            <option value ="flats to rent">Flats to Rent</option>
                            <option value ="activity">Activities</option>
                            <option value ="university">Universities</option>
                            <option value ="coffee break">Coffee Break</option>
                        </select>
                    </div>
                </td>
            </tr>
    
            <tr>
                <th></th>
                <td>
                    <button type="submit" onclick=alert("Submited!")>Submit</button>
                </td>
            </tr>
            </tbody>
        </table>
    </form>
</div>
{% endblock %}

templates/forum/published.html
{% extends 'forum/base.html' %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}

<div class="container" style="width:520px;margin: 0 auto;background: #e1e1e1;padding: 13px;">
    <h1>Register for the Forum</h1>
    
    {% if registered %}
        <strong>Thank you for registering!</strong>
        <a href="{% url 'forum:index' %}">Return to the homepage.</a><br /> <a href="{% url 'forum:logout' %}">Logout.</a><br />
    {% else %}
       <strong>Please register here!</strong> 
    {{ user_form.errors }}
    {{profile_form.errors}}
        <form role="form"  id="register_form" method="post" onsubmit="return register()" action="{% url 'forum:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
          
            <div class="form-group">
                <label class="required" for="id_username">
                Username:</label>
                <input class="form-control" id="id_username" maxlength="30"
                     name="username" type="text" />
                <span class="helptext">
                Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.
                </span>
            </div>
            <div class="form-group">
                <label class="required" for="id_email">
                E-mail:</label>
                <input class="form-control" id="id_email" name="email"
                     type="email" />
                    </div>
            <div class="form-group">
            <label class="required" for="id_password1">
                Password:</label>
                <input class="form-control" id="id_password1" name="password"
                    type="password" />
            </div>
             <div class="form-group">
                <label class="required" for="id_password2">
                    Password confirmation:</label>
                <input class="form-control" id="id_password2" name="password2"
                     type="password" />
                <span class="helptext">
                     Enter the same password as before, for verification.
               </span>
           </div>
      
    
        <div class="form-group">
            <label for="exampleFormControlFile1">Example file input</label>
            <input type="file" name="picture" class="form-control-file" id="exampleFormControlFile1">
          </div>
    
    
            <button type="submit" class="btn btn-dark">Register</button>
        </form>
        
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">message</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="content">
              
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    
    {% endif %}
    
    {% endblock %}

    {% block js %}
    <script src="/static/js/register.js"></script>
    {% endblock %}

templates/forum/register.html
{% extends 'forum/base.html' %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}

<div class="container" style="width:520px;margin: 0 auto;background: #e1e1e1;padding: 13px;">
    <h1>Register for the Forum</h1>
    
    {% if registered %}
        <strong>Thank you for registering!</strong>
        <a href="{% url 'forum:index' %}">Return to the homepage.</a><br /> <a href="{% url 'forum:logout' %}">Logout.</a><br />
    {% else %}
       <strong>Please register here!</strong> 
        <form role="form"  id="user_form" method="post" action="{% url 'forum:register' %}" enctype="multipart/form-data" onsubmit= "register();return false">
            {% csrf_token %}
          
            <div class="form-group">
                <label class="required" for="id_username">
                Username:</label>
                <input class="form-control" id="id_username" maxlength="30"
                     name="username" type="text" />
                <span class="helptext">
                Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.
                </span>
            </div>
            <div class="form-group">
                <label class="required" for="id_email">
                E-mail:</label>
                <input class="form-control" id="id_email" name="email"
                     type="email" />
                    </div>
            <div class="form-group">
            <label class="required" for="id_password1">
                Password:</label>
                <input class="form-control" id="id_password1" name="password"
                    type="password" />
            </div>
             <div class="form-group">
                <label class="required" for="id_password2">
                    Password confirmation:</label>
                <input class="form-control" id="id_password2" name="password2"
                     type="password" />
                <span class="helptext">
                     Enter the same password as before, for verification.
               </span>
           </div>
      
    
        <div class="form-group">
            <label for="exampleFormControlFile1">Example file input</label>
            <input type="file" name="picture" class="form-control-file" id="exampleFormControlFile1">
          </div>
    
    
            <button type="submit" class="btn btn-dark">Register</button>
        </form>
        
    </div>
    
    {% endif %}

</div>
<div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">message</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="content1">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block js %}
<script src="/static/js/register.js"></script>
    
    {% endblock %}